### ISSUE TITLE
Exception Handling einbauen?

### ISSUE THREAD

**Issue by n2code** [BigDaddy-Germany/WHOAMI#107]
```
Modul hat noch -626572 Millis
Modul hat noch -626575 Millis
Modul hat noch -626579 Millis
Start C:\Users\Besitzer\.activator\1.1.1\templates\7259c720-f2cc-437f-b85b-61610
508bb5f\src\main\java\HelloAkkaJava.java
Modul hat noch -626583 Millis
Modul hat noch -626585 Millis
Modul hat noch -626586 Millis
Modul hat noch -626588 Millis
Modul hat noch -626589 Millis
context [anonymous] 2:28 attribute topLanguage isn't defined
context [anonymous] 3:4 attribute moreWebLanguage isn't defined
6:11: premature EOF
context [anonymous] 2:28 attribute topLanguage isn't defined
context [anonymous] 3:4 attribute moreWebLanguage isn't defined
6:11: premature EOF
Exception in thread "main" org.stringtemplate.v4.compiler.STException
        at org.stringtemplate.v4.compiler.Compiler.reportMessageAndThrowSTExcept
ion(Compiler.java:213)
        at org.stringtemplate.v4.compiler.Compiler.compile(Compiler.java:143)
        at org.stringtemplate.v4.STGroup.compile(STGroup.java:446)
        at org.stringtemplate.v4.ST.<init>(ST.java:142)
        at org.stringtemplate.v4.ST.<init>(ST.java:136)
        at de.aima13.whoami.modules.syntaxcheck.SyntaxAnalyzer.getHtml(SyntaxAna
lyzer.java:140)
        at de.aima13.whoami.ReportCreator.createHtml(ReportCreator.java:98)
        at de.aima13.whoami.ReportCreator.getHtml(ReportCreator.java:74)
        at de.aima13.whoami.Whoami.main(Whoami.java:66)
```

**Comment by mdoerfler** [comment]
Kommt das nicht einfach nur daher, dass das String-Template dann falsch ist? Ich kann es ja einbauen, das is kein Problem

Und wegen #108 - Wie kommt es dazu, dass es hier plötzlich über 60000 Millis Laufzeit gibt?
