### ISSUE TITLE
Bugreport Array out of Bounds

### ISSUE THREAD

**Issue by n2code** [BigDaddy-Germany/WHOAMI#109]
```
Exception in thread "Thread-4" java.lang.ArrayIndexOutOfBoundsException: 2
    at de.aima13.whoami.modules.Food.getViewCountAndUrl(Food.java:462)
    at de.aima13.whoami.modules.Food.analyzeDelieveryServices(Food.java:289)
    at de.aima13.whoami.modules.Food.run(Food.java:146)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by momoXD007** [comment]
Schaus mir morgen an.
