### ISSUE TITLE
Bugreport NumberFormatException

### ISSUE THREAD

**Issue by n2code** [BigDaddy-Germany/WHOAMI#110]
```
Exception in thread "Thread-5" java.lang.NumberFormatException: Value out of range. Value:"148" Radix:10
    at java.lang.Byte.parseByte(Byte.java:150)
    at java.lang.Byte.parseByte(Byte.java:174)
    at de.aima13.whoami.modules.Music.scoreFavGenre(Music.java:350)
    at de.aima13.whoami.modules.Music.run(Music.java:111)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by IngMiad** [comment]
Oh okay. Wow, das ist ein ziemlich intelligenter Fehler ... :D
