### ISSUE TITLE
JSON Fehlerhaft?

### ISSUE THREAD

**Issue by mdoerfler** [BigDaddy-Germany/WHOAMI#149]
`Exception in thread "Thread-12" java.lang.RuntimeException: JSON fehlerhaft: /data/Games_Database.json
    at de.aima13.whoami.support.Utilities.loadDataFromJson(Utilities.java:57)
    at de.aima13.whoami.modules.gamesmod.GameCollector.<init>(GameCollector.java:29)
    at de.aima13.whoami.modules.gamesmod.Games.run(Games.java:188)
    at java.lang.Thread.run(Thread.java:745)`

**Comment by mdoerfler** [comment]
![image](https://cloud.githubusercontent.com/assets/7766452/4965201/f175dee0-6781-11e4-963a-6758fc25557e.png)
