### ISSUE TITLE
Score Changes after calculating results

### ISSUE THREAD

**Issue by mdoerfler** [BigDaddy-Germany/WHOAMI#151]
Nach der Laufzeit der run() Methode sind keine Änderungen von Scores mehr erlaubt. Ich werde die entsprechende Zeile aus deinem Modul mal temporär auskommentieren, sodass uns keine RuntimeException um die Ohren fliegt und das Ganze trotzdem zu den Results kommt. 

Du müsstest dich trotzdem darum kümmern, den Score an der richtigen Stelle zu erwähnen.

`Exception in thread "Thread-5" java.lang.RuntimeException: No score changes allowed after calculating the results!
    at de.aima13.whoami.GlobalData.changeScore(GlobalData.java:262)
    at de.aima13.whoami.modules.TopFive.prepareOutput(TopFive.java:167)
    at de.aima13.whoami.modules.TopFive.getCsvContent(TopFive.java:85)
    at de.aima13.whoami.CsvCreator.saveCsv(CsvCreator.java:43)
    at de.aima13.whoami.Whoami.run(Whoami.java:75)
    at java.lang.Thread.run(Thread.java:745)`

**Comment by marvinklose** [comment]
Sollte behoben sein
