### ISSUE TITLE
Encoding Probleme mit GlobalData

### ISSUE THREAD

**Issue by marvinklose** [BigDaddy-Germany/WHOAMI#174]
Critical : Exception in thread "Thread-11" java.lang.RuntimeException: Changing of not registered score.
 at de.aima13.whoami.GlobalData.changeScore(GlobalData.java:267)
 at de.aima13.whoami.modules.TopFive.checkScoreInfluence(TopFive.java:147)
 at de.aima13.whoami.modules.TopFive.run(TopFive.java:116)
 at java.lang.Thread.run(Thread.java:724)
Exception in thread "Thread-12" java.lang.RuntimeException: Changing of not registered score.
 at de.aima13.whoami.GlobalData.changeScore(GlobalData.java:267)
 at de.aima13.whoami.modules.syntaxcheck.SyntaxAnalyzer.run(SyntaxAnalyzer.java:431)
 at java.lang.Thread.run(Thread.java:724)
Exception in thread "Thread-7" java.lang.RuntimeException: Proposal of not registered data.
 at de.aima13.whoami.GlobalData.proposeData(GlobalData.java:227)
 at de.aima13.whoami.GlobalData.proposeData(GlobalData.java:203)
 at de.aima13.whoami.modules.Studienrichtung.run(Studienrichtung.java:198)
 at java.lang.Thread.run(Thread.java:724)

Vermutlich irgendwo ein Fehler,
"KurskÃ¼rzel".equals("Kurskürzel") => False

**Comment by marvinklose** [comment]
Fehler ist durch irgendein Kopiervorgang passiert. Und tritt wahrscheinlich nur lokal auf.
Lösung: Einfach nochmal neu tippen bei UTF8 Encoding
